#ifndef __GAMESTATUS_H__
#define __GAMESTATUS_H__

enum GAME_STATE {
    GAME_INACTIVE,
    GAME_PAUSE,
    GAME_INITIALIZE,
    GAME_ACTIVE
};

enum GAME_MODE {
    MODE_NORMAL,
    MODE_HARD,
};

#endif // __GAMESTATUS_H__