#################################
# HAM Makefile                   
# Created by Visual HAM          
#################################
include $(HAMDIR)/system/master.mak

#
# Set the name of your desired GBA image name here 
#
PROGNAME = dsound1

#
# Set a list of files you want to compile
#
OFILES += dsound1.o bfly.o sound2.o 

#######################################
# Standard Makefile targets start here 
#######################################
all : $(PROGNAME).$(EXT) clean

#
# Most Makefile targets are predefined for you, suchas
# vba, clean ... in the following file
#
include $(HAMDIR)/system/standard-targets.mak

#######################################
# custom  Makefile targets start here  
#######################################

#gfx: makefile
#	gfx2gba -t8 -m -fsrc gfx/*.bmp
