#####################################
# HAM Makefile
#
# Created by Visual HAM V2
# Get VHAM at www.console-dev.de
#####################################

include $(HAMDIR)/system/master.mak

#
# Set the name of your desired GBA image name here
#
PROGNAME = demo

#
# Compile using Krawall software (set to yes or no) ?
# Also specify if Krawall is registered (yes or no)
#
USE_KRAWALL=no
KRAWALL_IS_REGISTERED=no
KRAWALL_FILES=

#
# Set a list of files you want to compile 
# 
OFILES += main.o 

######################################
# Standard Makefile targets start here
######################################

all : $(PROGNAME).$(EXT) clean

#
# Most Makefile targets are predefined for you, suchas
# vba, clean ... in the following file
#
include $(HAMDIR)/system/standard-targets.mak

######################################
# custom  Makefile targets start here
######################################


gfx: makefile
#	gfx2gba -t8 -m -fsrc gfx\\*.bmp
#	gfx2gba -t8 -m -rs -fsrc gfx\\facerot.bmp
	



